package io.github.vedant7007.katori.ml.llm

import io.github.vedant7007.katori.data.food.FoodTextMatching

/**
 * Routes an utterance to LOG, ANSWER, SUGGEST or RECOMMEND deterministically where the words
 * decide it, and to the model only where they do not.
 *
 * WHY THE MODEL IS SECOND, ruled by Vedant on 20 September (`0027`). The classifier prompt
 * scored 23 of 53 on the phone, and three of its misroutes sent a QUESTION to LOG, which writes
 * a meal the person never ate into their diary: in the demo, beat 2 corrupts beat 1. Four
 * intents in a food-logging app is a decision, and the design claim of this product is that the
 * model does not decide. So: [decide] reads the markers; when exactly one intent's evidence is
 * present the intent is decided without a model call, which is also seconds off the hot path;
 * when the evidence is silent or conflicts, the model is consulted, and [accept] refuses a LOG
 * verdict on any sentence that carries a question marker, so the dangerous misroute cannot
 * happen whatever the model says.
 *
 * THE EVIDENCE, in precedence order:
 *   1. a certain log ([LogPrefilter.isCertainLog]): an eating word or a quantity, and no marker.
 *   2. HISTORY: a question about what they ate (a question marker with a past-tense eating word,
 *      or a diary word: today, yesterday, this week, my lunch, kal, aaj) -> ANSWER.
 *   3. PLATE NOW: a plate in front of them (having, eating, about to, kha raha, ippudu) -> SUGGEST.
 *   4. RECOMMEND: asking what THEY should eat (what should I eat, what to avoid, for more iron,
 *      to lose weight, kya khana chahiye, ke liye, emi tinali) -> RECOMMEND.
 *   5. a general question with none of the above (does, which, is) -> ANSWER (`0020`).
 * Two kinds of evidence at once is a conflict and goes to the model, restricted to those kinds.
 *
 * LANGUAGES. The demo runs in Hindi or Indian English, so the English and roman Hindi markers
 * are the ones that carry weight and are the ones Vedant can check himself. The roman Telugu
 * entries were generated by someone who does not read Telugu, are on the reviewer's sheet, and
 * are not load-bearing for the demo. A wrong marker here costs a model call or an "ask", never
 * a written meal: LOG is decided only by [LogPrefilter], and refused by [accept] on any question.
 *
 * MEASURED on the authored 53-case set by `IntentRouterTest`, which asserts no decided intent
 * is wrong and no non-LOG sentence is ever decided LOG, and prints how many go to the model.
 */
object IntentRouter {

    sealed interface Decision {
        /** The words decided it. No model call. */
        data class Decided(val intent: Intent, val evidence: String) : Decision
        /** The words were silent or conflicting; ask the model, and accept only one of [allowed]. */
        data class AskModel(val allowed: Set<Intent>, val why: String) : Decision
    }

    fun decide(transcript: String): Decision {
        if (LogPrefilter.isCertainLog(transcript)) return Decision.Decided(Intent.LOG, "a meal stated: an eating word or a quantity, no marker")
        val text = FoodTextMatching.normalise(transcript)
        if (text.isEmpty()) return Decision.AskModel(Intent.entries.toSet(), "empty")
        val words = text.split(' ')
        val question = LogPrefilter.hasMarker(transcript)
        val logWord = words.any { it in LogPrefilter.LOG_WORDS }

        val history = (question && logWord) || hit(text, words, HISTORY, HISTORY_PHRASES)
        val plateNow = hit(text, words, PLATE_NOW, PLATE_NOW_PHRASES)
        val recommend = hit(text, words, RECOMMEND, RECOMMEND_PHRASES)

        val evidence = buildList {
            if (history) add(Intent.ANSWER)
            if (plateNow) add(Intent.SUGGEST)
            if (recommend) add(Intent.RECOMMEND)
        }
        return when {
            evidence.size == 1 -> Decision.Decided(evidence.single(), evidenceName(evidence.single()))
            evidence.size > 1 -> Decision.AskModel(evidence.toSet(), "conflicting: ${evidence.joinToString()}")
            question -> Decision.Decided(Intent.ANSWER, "a general question")
            // "no rice today": the model may say anything but LOG.
            LogPrefilter.negatesFood(transcript) -> Decision.AskModel(Intent.entries.toSet() - Intent.LOG, "a food denied")
            // No marker and no eating word: "a plate of biryani and some raita". The model may
            // say any of the four; a LOG here is accepted because nothing says it is a question.
            else -> Decision.AskModel(Intent.entries.toSet(), "no evidence")
        }
    }

    /**
     * The model's verdict, checked against the words. A LOG on a sentence with a question marker
     * is refused (null: the caller asks the person), and a verdict outside what [decide] allowed
     * is refused the same way. Everything else is accepted as the model said it.
     */
    fun accept(modelSays: Intent, transcript: String): Intent? {
        // A LOG on a question, or on a sentence that says a food was NOT eaten, is refused
        // whatever the model says: the person is asked.
        if (modelSays == Intent.LOG && (LogPrefilter.hasMarker(transcript) || LogPrefilter.negatesFood(transcript))) return null
        val d = decide(transcript)
        return when (d) {
            is Decision.Decided -> d.intent
            is Decision.AskModel -> modelSays.takeIf { it in d.allowed }
        }
    }

    private fun hit(text: String, words: List<String>, single: Set<String>, phrases: List<String>) =
        words.any { it in single } || phrases.any { FoodTextMatching.containsAsWords(text, it) }

    private fun evidenceName(i: Intent) = when (i) {
        Intent.ANSWER -> "a question about what they ate"
        Intent.SUGGEST -> "a plate in front of them"
        Intent.RECOMMEND -> "asking what they should eat"
        Intent.LOG -> "log"
    }

    // --- ANSWER: their own history -------------------------------------------------------------
    internal val HISTORY: Set<String> = setOf(
        // "today" and "aaj" are deliberately absent: they are as often about the next meal
        // ("what should I eat today") as the last one, and a question about today's meals
        // carries "did I" or a past-tense eating word, which is caught above.
        "yesterday", "logged", "diary", "history", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday",
        // roman Hindi: yesterday, the day before; then Devanagari as the hi recogniser writes it
        "kal", "parso", "कल", "परसों", "पिछले", "पिछला", "पिछली",
        // roman Telugu, generated: today, yesterday, this week
        "ninna", "monna",
    )
    internal val HISTORY_PHRASES: List<String> = listOf(
        "did i", "have i", "had i", "i ate", "i had", "what did i", "this week", "last week", "this morning", "this month", "so far",
        "my lunch", "my breakfast", "my dinner", "my meals", "my meal", "my snack", "my diary",
        "maine kya", "maine kitna", "maine kitni", "kya khaya", "kitna khaya", "kya piya",
        "मैंने क्या", "मैंने कितना", "मैंने कितनी", "क्या खाया", "कितना खाया", "क्या पिया", "मेरे लंच", "मेरे नाश्ते", "मेरे खाने", "मेरे डिनर",
        "ee roju", "ee vaaram", "em tinnanu", "enti tinnanu", "entha tinnanu",
    )

    // --- SUGGEST: a plate in front of them -------------------------------------------------------
    internal val PLATE_NOW: Set<String> = setOf(
        "having", "eating", "making", "cooking", "ordering",
        // roman Hindi: now, eating (present); then Devanagari
        "abhi", "अभी",
        // roman Telugu, generated: now, eating
        "ippudu", "tintunna", "tintunnanu", "tintunnam", "chestunna", "chestunnanu",
    )
    internal val PLATE_NOW_PHRASES: List<String> = listOf(
        "about to", "going to eat", "going to have", "in front of me", "on my plate", "lunch is", "dinner is", "breakfast is", "snack is",
        "should i add", "can i add", "what goes with", "serve it with", "serve with", "go with", "along with this",
        "kha raha", "kha rahi", "kha rahe", "bana raha", "bana rahi", "khane wala", "khane wali", "add karun", "kya add",
        "खा रहा", "खा रही", "खा रहे", "बना रहा", "बना रही", "क्या ऐड", "ऐड करूँ", "ऐड करूं", "इसमें क्या", "क्या जोड़ूँ", "क्या जोड़ूं",
        "add cheyali", "inka emi",
    )

    // --- RECOMMEND: what should THEY eat ---------------------------------------------------------
    internal val RECOMMEND: Set<String> = setOf(
        "recommend", "suggest", "suggestion", "suggestions", "recommendation", "recommendations",
    )
    internal val RECOMMEND_PHRASES: List<String> = listOf(
        "should i eat", "should i have", "should i avoid", "should i take", "should i drink", "should i stop", "should i reduce",
        "what to eat", "what to avoid", "what to have", "what can i eat", "what can i have", "what could i eat",
        "what should i eat", "what should i have", "what should i avoid", "what should i take", "what should i drink",
        "what foods", "which foods", "which food", "foods help", "food helps", "foods for", "food for",
        "sources of", "source of", "good for me", "bad for me", "for me", "best for", "better for",
        "want to eat", "want to have", "i want", "something for", "can i eat", "can i have", "can i drink",
        "for more", "for less", "for better", "for lower", "for higher", "for extra",
        "to increase", "to lose", "to gain", "to reduce", "to lower", "to improve", "to boost", "to control", "to build",
        // roman Hindi
        "kya khana chahiye", "kya khaun", "kya khau", "kya khayein", "kya khaye", "kya lena chahiye", "kya lu", "kya loon",
        "ke liye", "badhane", "kam karne", "mere liye", "mujhe kya", "kya khana",
        "क्या खाना चाहिए", "क्या खाऊँ", "क्या खाऊं", "क्या लूँ", "क्या लूं", "के लिए", "बढ़ाने", "कम करने", "मेरे लिए", "मुझे क्या", "क्या खाना",
        // "kha sakta hoon" is "can I eat", not "ate": listed here so the HISTORY reading of "pi"
        // and "kha" as past tense becomes a conflict for the model rather than a wrong ANSWER.
        "kha sakta", "kha sakti", "pi sakta", "pi sakti", "le sakta", "le sakti",
        // roman Telugu, generated
        "emi tinali", "emi thinali", "kosam", "naaku emi", "em tinali",
    )
}
